name = "pincode checker"

client_id = "YOUR_SHOPIFY_CLIENT_ID"

application_url = "https://api.glomore.in"

embedded = true

[build]
automatically_update_urls_on_dev = true

[webhooks]
api_version = "2026-10"

[[webhooks.subscriptions]]
uri = "/webhooks/app/uninstalled"
topics = ["app/uninstalled"]

[[webhooks.subscriptions]]
uri = "/webhooks/app/scopes_update"
topics = ["app/scopes_update"]

[access_scopes]
scopes = "write_metaobject_definitions,write_metaobjects,write_products"

[auth]
redirect_urls = [
  "https://api.glomore.in/auth/callback"
]